Update patch set 4
Patch Set 4:

this commit breaks the script

❯ hardware/lineage/interfaces/update-makefiles.sh
Updating makefiles for vendor.lineage in /home/dianlujitao/Android/lineage-18.1/hardware/lineage/interfaces.
Updating vendor.lineage.biometrics.fingerprint.inscreen@1.0
Updating vendor.lineage.camera.motor@1.0
Updating vendor.lineage.fastcharge@1.0
Updating vendor.lineage.livedisplay@2.0
Updating vendor.lineage.motorola_health@1.0
Updating vendor.lineage.power@1.0
Updating vendor.lineage.powershare@1.0
Updating vendor.lineage.touch@1.0
ERROR: File at '/home/dianlujitao/Android/lineage-18.1/hardware/lineage/interfaces/motorola_health/1.0/types.hal' does not match expected package and/or version.
ERROR: Could not parse vendor.lineage.motorola_health@1.0::types. Aborting.
Command failed: hidl-gen -O "" -Landroidbp -rvendor.lineage:hardware/lineage/interfaces -randroid.hardware:hardware/interfaces -randroid.hidl:system/libhidl/transport  vendor.lineage.motorola_health@1.0
Updating vendor.lineage.trust@1.0

Patch-set: 4
CC: Gerrit User 10258 <10258@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>